version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    env_file:
      - ./front/.env.local
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
  
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
    command: flask run --host=0.0.0.0